ABOUT_RU = "Собран на Python 3\nМодульная архитектура\nУстойчив к нагрузкам. Масштабируем\nВстроенные: логирование, планировщик, двуязычный режим\nФункции: интеграция с каналом, обработка пользователей, задачи по расписанию\nАптайм: 24/7."

ABOUT_EN = "Built on Python 3\nModular architecture\nLoad-resistant. Scalable\nEmbedded: logging, scheduler, bilingual mode\nFunctions: channel integration, user processing, scheduled tasks\nUptime: 24/7"

MSG = {
    "ru": {
        "start": "Выбери язык / Choose your language",
        "status": "я здесь",
        "welcome": "зови меня Аш. я не про вежливость, я про результат 🔥\nтелеграм-бот может быть быстрым, умным и с характером.\nговорю на двух языках, веду новостной канал — и всё, что захочешь.\nстабильность? 24/7. я говорю меньше, чем делаю.",
        "menu": "Меню:",
        "pick_lang": "Выбери язык:",
        "catalog_title": "Catalog — боты, которые действительно работают.",
        "catalog_btn_simple": "Simple",
        "catalog_btn_simple_custom": "Simple Custom (this bot)",
        "catalog_btn_integrations": "Custom integrations",
        "catalog_btn_ai_ultra": "AI-powered Ultra",
        "catalog_btn_sale": "Акции",
        "catalog_btn_contact": "Contact",
        "card_simple": "Базовый Telegram-бот: команды, ответы, простая логика.\nПодходит для быстрых MVP и мини-сервисов.",
        "card_simple_custom": "Кастом на Python (как этот бот): канал-постинг, двуязычие, планировщик, логи.\nБез конструкторов — чистый код.",
        "card_integrations": "Интеграции: Google Sheets/API, webhooks, формы/лиды, нестандартные сценарии.\nАрхитектура под проект.",
        "card_ai_ultra": "Диалоги на ИИ, память, персонализация, сложные ветки.\nПремиум-уровень, по брифу.",
        "sale": "Временная акция: Simple Custom — $300 для первых 5. Потом — стандартные ставки.",
        "channel_here": "Канал",
        "one_news_intro": "Одна на вкус:",
        "go_channel": "Перейти в канал",
        "tip_title": "Поддержать Ash",
        "tip_desc": "Throw a star my way ✨",
        "tip_btn_1": "☕ Coffee",
        "tip_btn_2": "🍕 Pizza",
        "tip_btn_3": "🔥 Big Support",
        "thanks_tip": "Спасибо за поддержку. Зачтено. 🔥",
        "about": ABOUT_RU,
        "prev": "◀ Пред",
        "back_catalog": "Каталог",
        "next": "Дальше ▶",
        "back_main": "Главное меню",
        "back_to": "Назад"
    },
    "en": {
        "start": "Choose your language 👇",
        "status": "online",
        "welcome": "call me Ash. I'm not about etiquette — I'm about outcomes.\na Telegram bot can be fast, sharp, and with attitude.\nbilingual, runs a news channel — and whatever you need.\nuptime? 24/7. I talk less than I ship.",
        "menu": "Menu:",
        "pick_lang": "Choose language:",
        "catalog_title": "Catalog — bots that actually work.",
        "catalog_btn_simple": "Simple",
        "catalog_btn_simple_custom": "Simple Custom (this bot)",
        "catalog_btn_integrations": "Custom integrations",
        "catalog_btn_ai_ultra": "AI-powered Ultra",
        "catalog_btn_sale": "Promo",
        "catalog_btn_contact": "Contact",
        "card_simple": "Basic Telegram bot: commands, replies, simple logic.\nGreat for quick MVPs and mini-services.",
        "card_simple_custom": "Custom Python build (like this one): channel posting, bilingual, scheduler, logging.\nNo templates — clean code.",
        "card_integrations": "Integrations: Google Sheets/API, webhooks, forms/leads, custom flows.\nArchitecture tailored to your project.",
        "card_ai_ultra": "AI dialogues, memory, personalization, complex flows.\nPremium level, built to brief.",
        "sale": "Launch promo: Simple Custom — $300 for the first 5. Standard rates afterward.",
        "channel_here": "Channel",
        "one_news_intro": "One to taste:",
        "go_channel": "Go to channel",
        "tip_title": "Support Ash",
        "tip_desc": "Throw a star my way ✨",
        "tip_btn_1": "☕ Coffee",
        "tip_btn_2": "🍕 Pizza",
        "tip_btn_3": "🔥 Big Support",
        "thanks_tip": "Thanks for the support. Noted. 🔥",
        "about": ABOUT_EN,
        "prev": "◀ Prev",
        "back_catalog": "Catalog",
        "next": "Next ▶",
        "back_main": "Main menu",
        "back_to": "Back"
    }
}
